spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: org.postgresql.Driver
    druid:
      url: jdbc:postgresql://192.168.0.205:5432/festa
      username: festa
      password: tongruan.123
      initial-size: 10
      max-active: 30
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

    
  redis:
    open: false  # 是否开启redis缓存  true开启   false关闭
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456   # 密码（默认为空）
    timeout: 6000  # 连接超时时长（毫秒） 
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
    
  
  cache:
    type: redis
    

tr:
  jwt:
    # 加密秘钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # token有效时长，7天，单位秒
    expire: 604800
    header: token
  swagger:
    show: false
  upload:
     # 文件上传临时目录 为空则为 java.io.tempdir
    temp: 
    # 上传类型 local-本地文件,ftp-ftp,fastdfs-走fastdfs上传
    type: fastdfs 
    
 
#本地文件上传要配置的参数     
#    local:
#      upload_local_path: 

#FTP文件上传要配置的参数     
#    ftp:
        # ftp 的host地址，ip或者域名
#      host:
        # ftp 的端口,一般默认21
#      port:
        # ftp 账号
#      username:
        # ftp 密码
#      password:
        # ftp 上传文件目录
#      base:  
    fastDfs:
      # tracker 服务器地址 包含端口
      tracker_server: 114.116.30.229:22122
      # storage 服务器地址 包含端口 可以为空
      storage_server:
      # fastdfs 安装服务器对外的nginx暴漏地址
      nginx_url: http://114.116.30.229
  
    # 上传文件最终目录
#    path: d:/upload/
    # 是否直接发布到了nginx里,如果为false,则url为本地url
#    nginx: false
    # 上传文件框架的临时目录
#    temp: d:/tmp
    #应用上传文件最终的浏览地址  如果用的是nginx,则打开开关,地址指向nginx
#    url_server: http://localhost:8080/fdc-admin/file/img/
#    otfile: http://localhost:8080/fdc-admin/file/otfile
    qiniu: 
      endpoint:  
      accessKey:  
      secretKey:  
      bucketName:  
    minio: 
      endpoint: http://121.36.252.198:9000 
      accessKey: AKIAIOSFODNN7EXAMPLE
      secretKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      bucketName: festa
 
